name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: build
        run: pnpm build && touch docs/.vitepress/dist/.nojekyll && echo 'liuly.moe' > docs/.vitepress/dist/CNAME

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
